#!/bin/bash
# Azure DevOps Configuration
# Auto-generated by setup-azure-devops-secure.sh
# Created: Thu, Dec 25, 2025 12:29:13 AM

export AZURE_DEVOPS_ORG_URL="https://dev.azure.com/Nitish1766637423340"
export AZURE_DEVOPS_PROJECT="HooliMathHelper"
export AZURE_DEVOPS_REPO_NAME="HooliMathHelper"
export AZURE_DEVOPS_REPO_URL="https://Nitish1766637423340@dev.azure.com/Nitish1766637423340/HooliMathHelper/_git/HooliMathHelper"

echo -e "\033[0;32mAzure DevOps configuration loaded\033[0m"
echo -e "\033[0;36mOrganization: https://dev.azure.com/Nitish1766637423340\033[0m"
echo -e "\033[0;36mProject: HooliMathHelper\033[0m"
echo -e "\033[0;36mRepository: https://Nitish1766637423340@dev.azure.com/Nitish1766637423340/HooliMathHelper/_git/HooliMathHelper\033[0m"
