# IMPORTANT: Copy this file to the root of your CodeCommit repository
# Location: buildspec.yml (in the root directory)

# This file must be at the root of your repository for CodeBuild to find it
# The copy in config/ is just a template

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=$ECR_REPOSITORY_URL
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to private ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Note - Using ECR Public Gallery for base images - no authentication needed for public images

  build:
    commands:
      - echo Build started on `date`
      - cd app
      - npm install
      - CI=true npm test || echo "Tests completed"
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - cd ..
      - printf '[{"name":"logicworks-devops-container","imageUri":"'$REPOSITORY_URI':latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - app/**/*
